trigger:
  - main

pool:
  vmImage: 'ubuntu-24.04'

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Configurar Node.js'

  - script: |
      cd src/auth-service
      npm install
      npm test
    displayName: 'Probar auth-service'

  - script: |
      cd src/catalog-service
      npm install
      npm test
    displayName: 'Probar catalog-service'

  - script: |
      cd src/orders-service
      npm install
      npm test
    displayName: 'Probar orders-service'

  - script: |
      cd src/payments-service
      npm install
      npm test
    displayName: 'Probar payments-service'

  - script: |
      docker build -t belleza-auth:ci src/auth-service
    displayName: 'Construir imagen auth-service'

  - script: |
      docker build -t belleza-catalog:ci src/catalog-service
    displayName: 'Construir imagen catalog-service'

  - script: |
      docker build -t belleza-orders:ci src/orders-service
    displayName: 'Construir imagen orders-service'

  - script: |
      docker build -t belleza-payments:ci src/payments-service
    displayName: 'Construir imagen payments-service'

    - task: ArchiveFiles@2
  displayName: 'Empaquetar auth-service'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/auth-service'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/auth-service.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  displayName: 'Desplegar auth-service en Azure App Service'
  inputs:
    azureSubscription: 'sc-belleza-conceptual-azure'
    appType: 'webAppLinux'
    appName: 'app-belleza-conceptual-api'
    package: '$(Build.ArtifactStagingDirectory)/auth-service.zip'
    runtimeStack: 'NODE|22-lts'