BEGIN;

DROP SCHEMA IF EXISTS belleza_conceptual CASCADE;
CREATE SCHEMA belleza_conceptual;
SET search_path TO belleza_conceptual, public;

CREATE SEQUENCE seq_codigo_pedido START WITH 1 INCREMENT BY 1;

CREATE TABLE rol (
    id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    estado BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);

CREATE TABLE cliente (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    direccion TEXT NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categoria (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    descripcion VARCHAR(255),
    estado BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE producto (
    id_producto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INT NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria),
    CONSTRAINT ck_producto_precio
        CHECK (precio >= 0)
);

CREATE TABLE imagen_producto (
    id_imagen INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INT NOT NULL,
    url_imagen VARCHAR(500) NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_subida TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_imagen_producto
        FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE UNIQUE INDEX uq_imagen_principal_producto
    ON imagen_producto(id_producto)
    WHERE es_principal = TRUE;

CREATE TABLE inventario (
    id_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INT NOT NULL UNIQUE,
    cantidad_disponible INT NOT NULL DEFAULT 0,
    ultima_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventario_producto
        FOREIGN KEY (id_producto) REFERENCES producto(id_producto),
    CONSTRAINT ck_inventario_cantidad
        CHECK (cantidad_disponible >= 0)
);

CREATE TABLE movimiento_inventario (
    id_movimiento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario INT NOT NULL,
    id_usuario INT NOT NULL,
    tipo_movimiento VARCHAR(20) NOT NULL,
    cantidad INT NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    fecha_movimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movimiento_inventario
        FOREIGN KEY (id_inventario) REFERENCES inventario(id_inventario),
    CONSTRAINT fk_movimiento_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    CONSTRAINT ck_movimiento_tipo
        CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA', 'AJUSTE')),
    CONSTRAINT ck_movimiento_cantidad
        CHECK (cantidad <> 0)
);

CREATE TABLE carrito (
    id_carrito INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_carrito_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

CREATE TABLE linea_carrito (
    id_linea INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito INT NOT NULL,
    id_producto INT NOT NULL,
    cantidad INT NOT NULL DEFAULT 1,
    subtotal NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_linea_carrito
        FOREIGN KEY (id_carrito) REFERENCES carrito(id_carrito),
    CONSTRAINT fk_linea_producto
        FOREIGN KEY (id_producto) REFERENCES producto(id_producto),
    CONSTRAINT ck_linea_carrito_cantidad
        CHECK (cantidad > 0),
    CONSTRAINT ck_linea_carrito_subtotal
        CHECK (subtotal >= 0)
);

CREATE TABLE pedido (
    id_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    codigo_pedido VARCHAR(30) NOT NULL UNIQUE,
    fecha_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    estado_actual VARCHAR(30) NOT NULL DEFAULT 'Pendiente',
    metodo_pago_preferido VARCHAR(50) NOT NULL,
    CONSTRAINT fk_pedido_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT ck_pedido_total
        CHECK (total >= 0),
    CONSTRAINT ck_pedido_estado
        CHECK (
            estado_actual IN (
                'Pendiente',
                'En Coordinacion',
                'Pagado',
                'Enviado',
                'Completado',
                'Cancelado'
            )
        ),
    CONSTRAINT ck_pedido_metodo_pago
        CHECK (
            metodo_pago_preferido IN (
                'Enlace de pago',
                'Transferencia/Deposito',
                'Contra entrega'
            )
        )
);

CREATE TABLE detalle_pedido (
    id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL,
    id_producto INT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_detalle_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (id_producto) REFERENCES producto(id_producto),
    CONSTRAINT ck_detalle_cantidad
        CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_precio
        CHECK (precio_unitario >= 0),
    CONSTRAINT ck_detalle_subtotal
        CHECK (subtotal >= 0)
);

CREATE TABLE seguimiento_estado (
    id_seguimiento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL,
    id_usuario INT NOT NULL,
    estado VARCHAR(30) NOT NULL,
    fecha_cambio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT,
    CONSTRAINT fk_seguimiento_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT fk_seguimiento_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    CONSTRAINT ck_seguimiento_estado
        CHECK (
            estado IN (
                'Pendiente',
                'En Coordinacion',
                'Pagado',
                'Enviado',
                'Completado',
                'Cancelado'
            )
        )
);

CREATE TABLE pago (
    id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL UNIQUE,
    metodo_pago VARCHAR(50) NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    referencia VARCHAR(100),
    estado_pago VARCHAR(30) NOT NULL DEFAULT 'Pendiente',
    fecha_pago TIMESTAMP,
    CONSTRAINT fk_pago_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT ck_pago_metodo
        CHECK (
            metodo_pago IN (
                'Enlace de pago',
                'Transferencia/Deposito',
                'Contra entrega'
            )
        ),
    CONSTRAINT ck_pago_monto
        CHECK (monto >= 0),
    CONSTRAINT ck_pago_estado
        CHECK (estado_pago IN ('Pendiente', 'Verificado', 'Rechazado'))
);

CREATE TABLE entrega (
    id_entrega INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL UNIQUE,
    direccion_entrega TEXT NOT NULL,
    tipo_envio VARCHAR(50) NOT NULL,
    costo_envio NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    estado_entrega VARCHAR(30) NOT NULL DEFAULT 'Preparando',
    fecha_coordinada TIMESTAMP,
    CONSTRAINT fk_entrega_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT ck_entrega_tipo
        CHECK (
            tipo_envio IN (
                'Mensajería Local',
                'Envío Departamental',
                'Recolección en sucursal'
            )
        ),
    CONSTRAINT ck_entrega_costo
        CHECK (costo_envio >= 0),
    CONSTRAINT ck_entrega_estado
        CHECK (
            estado_entrega IN (
                'Preparando',
                'En Ruta',
                'Entregado',
                'Devuelto'
            )
        )
);

CREATE TABLE notificacion (
    id_notificacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL,
    tipo_notificacion VARCHAR(50) NOT NULL,
    destinatario VARCHAR(150) NOT NULL,
    mensaje TEXT NOT NULL,
    estado_envio VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
    fecha_envio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notificacion_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT ck_notificacion_tipo
        CHECK (
            tipo_notificacion IN (
                'Confirmacion_Pedido',
                'Aviso_Ventas',
                'Pago_Validado'
            )
        ),
    CONSTRAINT ck_notificacion_estado
        CHECK (estado_envio IN ('Enviado', 'Fallido', 'Pendiente'))
);

CREATE TABLE reporte (
    id_reporte INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL,
    tipo_reporte VARCHAR(80) NOT NULL,
    fecha_generacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    parametros_filtro JSON,
    CONSTRAINT fk_reporte_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    CONSTRAINT ck_reporte_tipo
        CHECK (
            tipo_reporte IN (
                'Ventas_Periodo',
                'Rotacion_Inventario',
                'Pedidos_Pendientes'
            )
        )
);

CREATE INDEX idx_producto_categoria
    ON producto(id_categoria);

CREATE INDEX idx_producto_estado
    ON producto(estado_activo);

CREATE INDEX idx_movimiento_inventario_fecha
    ON movimiento_inventario(id_inventario, fecha_movimiento DESC);

CREATE INDEX idx_carrito_cliente
    ON carrito(id_cliente);

CREATE INDEX idx_linea_carrito_producto
    ON linea_carrito(id_producto);

CREATE INDEX idx_pedido_cliente_fecha
    ON pedido(id_cliente, fecha_pedido DESC);

CREATE INDEX idx_pedido_estado
    ON pedido(estado_actual);

CREATE INDEX idx_detalle_pedido_pedido
    ON detalle_pedido(id_pedido);

CREATE INDEX idx_seguimiento_pedido_fecha
    ON seguimiento_estado(id_pedido, fecha_cambio DESC);

CREATE INDEX idx_notificacion_estado
    ON notificacion(estado_envio);

CREATE INDEX idx_entrega_estado
    ON entrega(estado_entrega);

COMMIT;

SET search_path TO belleza_conceptual, public;

CREATE OR REPLACE FUNCTION fn_stock_disponible(p_id_producto INT)
RETURNS INT
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_stock INT;
BEGIN
    SELECT cantidad_disponible
      INTO v_stock
      FROM belleza_conceptual.inventario
     WHERE id_producto = p_id_producto;

    RETURN COALESCE(v_stock, 0);
END;
$$;

CREATE OR REPLACE FUNCTION fn_calcular_total_pedido(p_id_pedido INT)
RETURNS NUMERIC(10,2)
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(SUM(subtotal), 0.00)::NUMERIC(10,2)
      FROM detalle_pedido
     WHERE id_pedido = p_id_pedido;
$$;

CREATE OR REPLACE FUNCTION fn_generar_codigo_pedido()
RETURNS VARCHAR(30)
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
    v_numero BIGINT;
BEGIN
    v_numero := nextval('belleza_conceptual.seq_codigo_pedido');

    RETURN 'PED-' ||
           TO_CHAR(CURRENT_DATE, 'YYYY') ||
           '-' ||
           LPAD(v_numero::TEXT, 4, '0');
END;
$$;

SET search_path TO belleza_conceptual, public;

CREATE OR REPLACE FUNCTION tg_calcular_subtotal_carrito()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_precio NUMERIC(10,2);
BEGIN
    SELECT precio
      INTO v_precio
      FROM producto
     WHERE id_producto = NEW.id_producto
       AND estado_activo = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'El producto % no existe o está inactivo', NEW.id_producto;
    END IF;

    NEW.subtotal := ROUND(v_precio * NEW.cantidad, 2);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_linea_carrito_subtotal
BEFORE INSERT OR UPDATE OF id_producto, cantidad
ON linea_carrito
FOR EACH ROW
EXECUTE FUNCTION tg_calcular_subtotal_carrito();

CREATE OR REPLACE FUNCTION tg_preparar_detalle_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_precio NUMERIC(10,2);
BEGIN
    IF TG_OP = 'INSERT'
       OR NEW.id_producto IS DISTINCT FROM OLD.id_producto THEN

        SELECT precio
          INTO v_precio
          FROM producto
         WHERE id_producto = NEW.id_producto
           AND estado_activo = TRUE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'El producto % no existe o está inactivo', NEW.id_producto;
        END IF;

        NEW.precio_unitario := v_precio;
    END IF;

    NEW.subtotal := ROUND(NEW.precio_unitario * NEW.cantidad, 2);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_detalle_pedido_preparar
BEFORE INSERT OR UPDATE OF id_producto, cantidad
ON detalle_pedido
FOR EACH ROW
EXECUTE FUNCTION tg_preparar_detalle_pedido();

CREATE OR REPLACE FUNCTION tg_recalcular_total_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        UPDATE pedido
           SET total = fn_calcular_total_pedido(OLD.id_pedido)
         WHERE id_pedido = OLD.id_pedido;
        RETURN OLD;
    END IF;

    UPDATE pedido
       SET total = fn_calcular_total_pedido(NEW.id_pedido)
     WHERE id_pedido = NEW.id_pedido;

    IF TG_OP = 'UPDATE' AND OLD.id_pedido IS DISTINCT FROM NEW.id_pedido THEN
        UPDATE pedido
           SET total = fn_calcular_total_pedido(OLD.id_pedido)
         WHERE id_pedido = OLD.id_pedido;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_detalle_pedido_total
AFTER INSERT OR UPDATE OR DELETE
ON detalle_pedido
FOR EACH ROW
EXECUTE FUNCTION tg_recalcular_total_pedido();

CREATE OR REPLACE FUNCTION tg_actualizar_fecha_inventario()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.ultima_actualizacion := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_inventario_fecha
BEFORE UPDATE OF cantidad_disponible
ON inventario
FOR EACH ROW
EXECUTE FUNCTION tg_actualizar_fecha_inventario();

SET search_path TO belleza_conceptual, public;

CREATE OR REPLACE PROCEDURE sp_crear_pedido(
    IN p_id_cliente INT,
    IN p_metodo_pago VARCHAR(50),
    IN p_items JSONB,
    INOUT p_id_pedido INT,
    INOUT p_codigo_pedido VARCHAR(30)
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item JSONB;
    v_id_producto INT;
    v_cantidad INT;
    v_stock INT;
BEGIN
    IF p_items IS NULL
       OR jsonb_typeof(p_items) <> 'array'
       OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'El pedido debe contener al menos un producto';
    END IF;

    IF p_metodo_pago NOT IN (
        'Enlace de pago',
        'Transferencia/Deposito',
        'Contra entrega'
    ) THEN
        RAISE EXCEPTION 'Método de pago no válido: %', p_metodo_pago;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM cliente
         WHERE id_cliente = p_id_cliente
    ) THEN
        RAISE EXCEPTION 'El cliente % no existe', p_id_cliente;
    END IF;

    p_codigo_pedido := fn_generar_codigo_pedido();

    INSERT INTO pedido (
        id_cliente,
        codigo_pedido,
        metodo_pago_preferido
    )
    VALUES (
        p_id_cliente,
        p_codigo_pedido,
        p_metodo_pago
    )
    RETURNING id_pedido INTO p_id_pedido;

    FOR v_item IN
        SELECT value
          FROM jsonb_array_elements(p_items)
    LOOP
        v_id_producto := (v_item ->> 'id_producto')::INT;
        v_cantidad := (v_item ->> 'cantidad')::INT;

        IF v_id_producto IS NULL OR v_cantidad IS NULL OR v_cantidad <= 0 THEN
            RAISE EXCEPTION 'Item inválido dentro del pedido: %', v_item;
        END IF;

        IF NOT EXISTS (
            SELECT 1
              FROM producto
             WHERE id_producto = v_id_producto
               AND estado_activo = TRUE
        ) THEN
            RAISE EXCEPTION 'El producto % no existe o está inactivo', v_id_producto;
        END IF;

        v_stock := belleza_conceptual.fn_stock_disponible(v_id_producto);

        IF v_stock < v_cantidad THEN
            RAISE EXCEPTION
                'Stock insuficiente para producto %. Disponible: %, solicitado: %',
                v_id_producto, v_stock, v_cantidad;
        END IF;

        INSERT INTO detalle_pedido (
            id_pedido,
            id_producto,
            cantidad,
            precio_unitario,
            subtotal
        )
        VALUES (
            p_id_pedido,
            v_id_producto,
            v_cantidad,
            0,
            0
        );
    END LOOP;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_registrar_movimiento_inventario(
    IN p_id_producto INT,
    IN p_id_usuario INT,
    IN p_tipo_movimiento VARCHAR(20),
    IN p_cantidad INT,
    IN p_motivo VARCHAR(255)
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_inventario INT;
    v_stock_actual INT;
    v_nuevo_stock INT;
    v_movimiento INT;
BEGIN
    IF p_tipo_movimiento NOT IN ('ENTRADA', 'SALIDA', 'AJUSTE') THEN
        RAISE EXCEPTION 'Tipo de movimiento no válido: %', p_tipo_movimiento;
    END IF;

    IF p_cantidad = 0 THEN
        RAISE EXCEPTION 'La cantidad no puede ser cero';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM usuario
         WHERE id_usuario = p_id_usuario
           AND estado = TRUE
    ) THEN
        RAISE EXCEPTION 'Usuario % inexistente o inactivo', p_id_usuario;
    END IF;

    SELECT id_inventario, cantidad_disponible
      INTO v_id_inventario, v_stock_actual
      FROM inventario
     WHERE id_producto = p_id_producto
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe inventario para el producto %', p_id_producto;
    END IF;

    CASE p_tipo_movimiento
        WHEN 'ENTRADA' THEN
            v_movimiento := ABS(p_cantidad);
            v_nuevo_stock := v_stock_actual + v_movimiento;

        WHEN 'SALIDA' THEN
            v_movimiento := -ABS(p_cantidad);
            v_nuevo_stock := v_stock_actual + v_movimiento;

        WHEN 'AJUSTE' THEN
            v_movimiento := p_cantidad;
            v_nuevo_stock := v_stock_actual + v_movimiento;
    END CASE;

    IF v_nuevo_stock < 0 THEN
        RAISE EXCEPTION
            'La operación dejaría inventario negativo. Stock actual: %, movimiento: %',
            v_stock_actual, v_movimiento;
    END IF;

    UPDATE inventario
       SET cantidad_disponible = v_nuevo_stock
     WHERE id_inventario = v_id_inventario;

    INSERT INTO movimiento_inventario (
        id_inventario,
        id_usuario,
        tipo_movimiento,
        cantidad,
        motivo
    )
    VALUES (
        v_id_inventario,
        p_id_usuario,
        p_tipo_movimiento,
        v_movimiento,
        p_motivo
    );
END;
$$;

CREATE OR REPLACE PROCEDURE sp_cambiar_estado_pedido(
    IN p_id_pedido INT,
    IN p_id_usuario INT,
    IN p_nuevo_estado VARCHAR(30),
    IN p_observaciones TEXT DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_nuevo_estado NOT IN (
        'Pendiente',
        'En Coordinacion',
        'Pagado',
        'Enviado',
        'Completado',
        'Cancelado'
    ) THEN
        RAISE EXCEPTION 'Estado no válido: %', p_nuevo_estado;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM usuario
         WHERE id_usuario = p_id_usuario
           AND estado = TRUE
    ) THEN
        RAISE EXCEPTION 'Usuario % inexistente o inactivo', p_id_usuario;
    END IF;

    UPDATE pedido
       SET estado_actual = p_nuevo_estado
     WHERE id_pedido = p_id_pedido;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Pedido % no encontrado', p_id_pedido;
    END IF;

    INSERT INTO seguimiento_estado (
        id_pedido,
        id_usuario,
        estado,
        observaciones
    )
    VALUES (
        p_id_pedido,
        p_id_usuario,
        p_nuevo_estado,
        p_observaciones
    );
END;
$$;

CREATE OR REPLACE PROCEDURE sp_registrar_pago(
    IN p_id_pedido INT,
    IN p_metodo_pago VARCHAR(50),
    IN p_monto NUMERIC(10,2),
    IN p_referencia VARCHAR(100),
    IN p_estado_pago VARCHAR(30)
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_metodo_pago NOT IN (
        'Enlace de pago',
        'Transferencia/Deposito',
        'Contra entrega'
    ) THEN
        RAISE EXCEPTION 'Método de pago no válido: %', p_metodo_pago;
    END IF;

    IF p_estado_pago NOT IN ('Pendiente', 'Verificado', 'Rechazado') THEN
        RAISE EXCEPTION 'Estado de pago no válido: %', p_estado_pago;
    END IF;

    IF p_monto < 0 THEN
        RAISE EXCEPTION 'El monto no puede ser negativo';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pedido
         WHERE id_pedido = p_id_pedido
    ) THEN
        RAISE EXCEPTION 'Pedido % no encontrado', p_id_pedido;
    END IF;

    INSERT INTO pago (
        id_pedido,
        metodo_pago,
        monto,
        referencia,
        estado_pago,
        fecha_pago
    )
    VALUES (
        p_id_pedido,
        p_metodo_pago,
        p_monto,
        p_referencia,
        p_estado_pago,
        CASE
            WHEN p_estado_pago = 'Verificado' THEN CURRENT_TIMESTAMP
            ELSE NULL
        END
    )
    ON CONFLICT (id_pedido)
    DO UPDATE SET
        metodo_pago = EXCLUDED.metodo_pago,
        monto = EXCLUDED.monto,
        referencia = EXCLUDED.referencia,
        estado_pago = EXCLUDED.estado_pago,
        fecha_pago = CASE
            WHEN EXCLUDED.estado_pago = 'Verificado'
                THEN CURRENT_TIMESTAMP
            ELSE pago.fecha_pago
        END;
END;
$$;

SET search_path TO belleza_conceptual, public;

CREATE OR REPLACE VIEW vw_catalogo_productos AS
SELECT
    p.id_producto,
    p.nombre AS producto,
    c.id_categoria,
    c.nombre AS categoria,
    p.descripcion,
    p.precio,
    COALESCE(i.cantidad_disponible, 0) AS cantidad_disponible,
    (COALESCE(i.cantidad_disponible, 0) > 0) AS disponible,
    img.url_imagen AS imagen_principal
FROM producto p
JOIN categoria c
  ON c.id_categoria = p.id_categoria
LEFT JOIN inventario i
  ON i.id_producto = p.id_producto
LEFT JOIN LATERAL (
    SELECT ip.url_imagen
      FROM imagen_producto ip
     WHERE ip.id_producto = p.id_producto
     ORDER BY ip.es_principal DESC, ip.id_imagen ASC
     LIMIT 1
) img ON TRUE
WHERE p.estado_activo = TRUE
  AND c.estado = TRUE;

CREATE OR REPLACE VIEW vw_inventario_actual AS
SELECT
    i.id_inventario,
    p.id_producto,
    p.nombre AS producto,
    c.nombre AS categoria,
    i.cantidad_disponible,
    i.ultima_actualizacion,
    p.estado_activo
FROM inventario i
JOIN producto p
  ON p.id_producto = i.id_producto
JOIN categoria c
  ON c.id_categoria = p.id_categoria;

CREATE OR REPLACE VIEW vw_pedidos_resumen AS
SELECT
    p.id_pedido,
    p.codigo_pedido,
    p.fecha_pedido,
    c.id_cliente,
    c.nombre AS cliente,
    c.telefono,
    c.email,
    p.total,
    p.estado_actual,
    p.metodo_pago_preferido,
    pg.estado_pago,
    pg.monto AS monto_pago,
    e.tipo_envio,
    e.estado_entrega,
    e.fecha_coordinada
FROM pedido p
JOIN cliente c
  ON c.id_cliente = p.id_cliente
LEFT JOIN pago pg
  ON pg.id_pedido = p.id_pedido
LEFT JOIN entrega e
  ON e.id_pedido = p.id_pedido;

CREATE OR REPLACE VIEW vw_historial_pedido AS
SELECT
    p.codigo_pedido,
    s.id_seguimiento,
    s.estado,
    s.fecha_cambio,
    u.id_usuario,
    u.nombre AS usuario,
    s.observaciones
FROM seguimiento_estado s
JOIN pedido p
  ON p.id_pedido = s.id_pedido
JOIN usuario u
  ON u.id_usuario = s.id_usuario;

SET search_path TO belleza_conceptual, public;

INSERT INTO rol (nombre, descripcion)
VALUES
    ('Administrador', 'Administración general de la tienda en línea'),
    ('Personal de ventas', 'Seguimiento de pedidos, pagos y atención comercial'),
    ('Inventario', 'Gestión y actualización de existencias');


-- ============================================================
-- DATOS DEMO PARA CATÁLOGO Y PRUEBAS FUNCIONALES
-- ============================================================

INSERT INTO belleza_conceptual.categoria
(nombre, descripcion, estado)
VALUES
('Cuidado facial', 'Productos para limpieza, hidratacion y cuidado del rostro', true),
('Maquillaje', 'Productos cosmeticos para rostro, ojos y labios', true),
('Cuidado capilar', 'Productos para limpieza, tratamiento y cuidado del cabello', true);

INSERT INTO belleza_conceptual.producto
(id_categoria, nombre, descripcion, precio, estado_activo)
VALUES
(1, 'Limpiador Facial', 'Limpiador suave para uso diario', 85.00, true),
(1, 'Crema Hidratante', 'Crema hidratante para rostro', 120.00, true),
(2, 'Labial Mate', 'Labial de acabado mate', 75.00, true),
(2, 'Base Liquida', 'Base liquida de cobertura media', 145.00, true),
(3, 'Shampoo Reparador', 'Shampoo para cabello seco o danado', 95.00, true),
(3, 'Tratamiento Capilar', 'Tratamiento nutritivo para el cabello', 135.00, true);

INSERT INTO belleza_conceptual.inventario
(id_producto, cantidad_disponible)
VALUES
(1, 20),
(2, 15),
(3, 30),
(4, 10),
(5, 25),
(6, 12);